pool:
  vmImage: 'ubuntu-latest'
  
steps:
- checkout: self

- task: DownloadSecureFile@1
  name: "keystore"
  inputs:
    secureFile: 'linphone-keystore.jks'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: chmod +x gradlew
  displayName: 'Grant execute permission for gradlew'


#- script: ./gradlew assembleRelease
#  displayName: 'Build with Gradle'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '-DKEYSTORE_ALIAS=$(KEYSTORE_ALIAS) -DKEYSTORE_PASSWORD=$(KEYSTORE_PASSWORD)'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'app/build/outputs'
    ArtifactName: 'apk-debug'
    publishLocation: 'container'